# Generated by Django 4.2.5 on 2023-10-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(default='Texto predeterminado'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
